Add CRD recommendationRule
gocrane/api pull request #58
Opened 2022-07-18 07:20 UTC by qmhu

2022-07-18 08:42 UTC, qmhu commented
> 1. How to describe a recommendation flow run only once?
runInterval: 0
> 2. How do I let the recommendation framework know what recommendation process I need to use
RecommendationRule defines which resources are needed for recommendation. RecommenderConfiguration defines which recommenders are enabled and will be trigger for recommendation process.
> 3. How to expand to non-GVK resources?
Give an example ?

2022-07-18 09:15 UTC, xieydd commented
> > 1. How to describe a recommendation flow run only once?
> >    runInterval: 0
> > 2. How do I let the recommendation framework know what recommendation process I need to use
> >    RecommendationRule defines which resources are needed for recommendation. RecommenderConfiguration defines which recommenders are enabled and will be trigger for recommendation process.
> > 3. How to expand to non-GVK resources?
> >    Give an example ?

2. Which trigger will be work, i think not all recommender.
3. CLB Service in https://github.com/gocrane/crane/pull/420.

2022-07-19 03:37 UTC, qmhu commented
> > > 1. How to describe a recommendation flow run only once?
> > >    runInterval: 0
> > > 2. How do I let the recommendation framework know what recommendation process I need to use
> > >    RecommendationRule defines which resources are needed for recommendation. RecommenderConfiguration defines which recommenders are enabled and will be trigger for recommendation process.
> > > 3. How to expand to non-GVK resources?
> > >    Give an example ?
> 
> 2. Which trigger will be work, i think not all recommender.
> 3. CLB Service in [Add types for recommenderConfiguration crane#420](https://github.com/gocrane/crane/pull/420).

Use recommender's name to link to RecommenderConfiguration now. Pls take a look again.

2022-07-19 06:15 UTC, merged

2022-07-19 06:18 UTC, xieydd requested changes

2022-07-19 06:18 UTC, xieydd commented on analysis/v1alpha1/types.go
> +// RecommendationRule represents the configuration of an RecommendationRule object.
Suggest change to `RecommendationRule is the rule to select  kubernetes resource and recommender.`

2022-07-19 06:18 UTC, xieydd commented on analysis/v1alpha1/types.go
> +	// +optional
spec is optional?

2022-07-19 06:18 UTC, xieydd commented on analysis/v1alpha1/types.go
> +	// RunInterval between two recommendation
can we point out the default interval?

2022-07-19 06:18 UTC, xieydd commented on analysis/v1alpha1/types.go
> +
delete the row

2022-07-19 06:18 UTC, xieydd commented on analysis/v1alpha1/types.go
> +	Recommendations []RecommendationMission `json:"recommendations,omitempty"`
why we use recommendation mission?